import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Upload, FileText, Camera, AlertCircle, CheckCircle, Download } from 'lucide-react';
import Button from '../components/UI/Button';

const Scan: React.FC = () => {
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysisResult, setAnalysisResult] = useState<any>(null);
  const [language, setLanguage] = useState<'en' | 'ur'>('en');

  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      setUploadedFile(file);
      analyzeDocument(file);
    }
  };

  const analyzeDocument = (file: File) => {
    setIsAnalyzing(true);
    
    // Simulate document analysis
    setTimeout(() => {
      setAnalysisResult({
        documentType: "Nikah Nama",
        rightsFound: [
          {
            title: "Mehr (Dower) Amount",
            status: "found",
            description: "Your Nikah Nama includes a Mehr amount of PKR 50,000",
            urduDescription: "آپ کے نکاح نامے میں پچاس ہزار روپے مہر کی رقم شامل ہے"
          },
          {
            title: "Right to Work",
            status: "found",
            description: "Your contract allows you to work after marriage",
            urduDescription: "آپ کے معاہدے میں شادی کے بعد کام کرنے کی اجازت ہے"
          },
          {
            title: "Maintenance Rights",
            status: "missing",
            description: "No specific maintenance clause found - this should be included",
            urduDescription: "مخصوص نفقہ کی شق نہیں ملی - یہ شامل ہونی چاہیے"
          },
          {
            title: "Divorce Rights",
            status: "limited",
            description: "Limited divorce rights specified - you may have additional rights under law",
            urduDescription: "محدود طلاق کے حقوق بیان کیے گئے - قانون کے تحت آپ کے اضافی حقوق ہو سکتے ہیں"
          }
        ],
        recommendations: [
          "Consult with a family law expert about missing maintenance clause",
          "Consider adding specific provisions for your rights",
          "Keep this document secure and accessible"
        ]
      });
      setIsAnalyzing(false);
    }, 3000);
  };

  const downloadReport = () => {
    if (!analysisResult) return;
    
    const report = `
NIKAH NAMA ANALYSIS REPORT
Generated by Haq Legal Rights Assistant

Document Type: ${analysisResult.documentType}
Analysis Date: ${new Date().toLocaleDateString()}

RIGHTS ANALYSIS:
${analysisResult.rightsFound.map((right: any, index: number) => `
${index + 1}. ${right.title}
   Status: ${right.status.toUpperCase()}
   Description: ${right.description}
`).join('')}

RECOMMENDATIONS:
${analysisResult.recommendations.map((rec: string, index: number) => `${index + 1}. ${rec}`).join('\n')}

---
This analysis is for informational purposes only. Please consult with a qualified lawyer for legal advice.
    `;
    
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'nikah-nama-analysis.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-[#FAFAFA] py-8">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center mb-12"
        >
          <h1 className="text-4xl sm:text-5xl font-bold text-[#333333] mb-6">
            Document Scanner
          </h1>
          <h2 className="text-3xl sm:text-4xl font-bold text-[#F06292] mb-6">
            دستاویز اسکینر
          </h2>
          <p className="text-xl text-[#333333] max-w-3xl mx-auto leading-relaxed mb-4">
            Upload your Nikah Nama, employment contract, or any legal document to discover your rights
          </p>
          <p className="text-lg text-[#333333] max-w-3xl mx-auto leading-relaxed">
            اپنے حقوق دریافت کرنے کے لیے نکاح نامہ، ملازمت کا معاہدہ، یا کوئی قانونی دستاویز اپ لوڈ کریں
          </p>
          
          <div className="mt-6">
            <button
              onClick={() => setLanguage(language === 'en' ? 'ur' : 'en')}
              className="px-4 py-2 bg-[#CE93D8] text-white rounded-lg hover:bg-[#BA68C8] transition-colors"
            >
              {language === 'en' ? 'اردو میں پڑھیں' : 'Read in English'}
            </button>
          </div>
        </motion.div>

        {/* Upload Section */}
        {!uploadedFile && (
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-white rounded-2xl shadow-lg p-8 mb-8"
          >
            <div className="border-2 border-dashed border-[#CE93D8] rounded-xl p-12 text-center">
              <div className="bg-[#F06292] p-4 rounded-full w-fit mx-auto mb-6">
                <Upload className="h-12 w-12 text-white" />
              </div>
              
              <h3 className="text-2xl font-bold text-[#333333] mb-4">
                {language === 'en' ? 'Upload Your Document' : 'اپنی دستاویز اپ لوڈ کریں'}
              </h3>
              
              <p className="text-[#333333] mb-8 max-w-md mx-auto">
                {language === 'en' 
                  ? 'Supported formats: PDF, JPG, PNG. Maximum size: 10MB'
                  : 'معاونت شدہ فارمیٹس: PDF، JPG، PNG۔ زیادہ سے زیادہ سائز: 10MB'
                }
              </p>
              
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <label className="cursor-pointer">
                  <input
                    type="file"
                    accept=".pdf,.jpg,.jpeg,.png"
                    onChange={handleFileUpload}
                    className="hidden"
                  />
                  <Button variant="primary" size="lg" icon={FileText}>
                    {language === 'en' ? 'Choose File' : 'فائل منتخب کریں'}
                  </Button>
                </label>
                
                <Button variant="secondary" size="lg" icon={Camera}>
                  {language === 'en' ? 'Take Photo' : 'تصویر لیں'}
                </Button>
              </div>
            </div>
            
            <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-6 text-center">
              <div className="p-6 bg-[#FAFAFA] rounded-xl">
                <FileText className="h-8 w-8 text-[#F06292] mx-auto mb-3" />
                <h4 className="font-semibold text-[#333333] mb-2">Nikah Nama</h4>
                <p className="text-sm text-[#333333] opacity-80">Discover your matrimonial rights</p>
              </div>
              <div className="p-6 bg-[#FAFAFA] rounded-xl">
                <FileText className="h-8 w-8 text-[#CE93D8] mx-auto mb-3" />
                <h4 className="font-semibold text-[#333333] mb-2">Employment Contract</h4>
                <p className="text-sm text-[#333333] opacity-80">Understand workplace rights</p>
              </div>
              <div className="p-6 bg-[#FAFAFA] rounded-xl">
                <FileText className="h-8 w-8 text-[#FFCA28] mx-auto mb-3" />
                <h4 className="font-semibold text-[#333333] mb-2">Legal Agreement</h4>
                <p className="text-sm text-[#333333] opacity-80">Analyze any legal document</p>
              </div>
            </div>
          </motion.div>
        )}

        {/* Analysis Progress */}
        {isAnalyzing && (
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-white rounded-2xl shadow-lg p-8 text-center"
          >
            <div className="bg-[#FFCA28] p-4 rounded-full w-fit mx-auto mb-6 animate-pulse">
              <FileText className="h-12 w-12 text-white" />
            </div>
            <h3 className="text-2xl font-bold text-[#333333] mb-4">
              {language === 'en' ? 'Analyzing Your Document...' : 'آپ کی دستاویز کا تجزیہ کر رہے ہیں...'}
            </h3>
            <p className="text-[#333333] mb-8">
              {language === 'en' 
                ? 'Our AI is carefully reviewing your document to identify your legal rights'
                : 'ہمارا اے آئی آپ کے قانونی حقوق کی شناخت کے لیے آپ کی دستاویز کا بغور سے جائزہ لے رہا ہے'
              }
            </p>
            <div className="flex justify-center space-x-2">
              <div className="w-3 h-3 bg-[#F06292] rounded-full animate-bounce"></div>
              <div className="w-3 h-3 bg-[#CE93D8] rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></div>
              <div className="w-3 h-3 bg-[#FFCA28] rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
            </div>
          </motion.div>
        )}

        {/* Analysis Results */}
        {analysisResult && !isAnalyzing && (
          <motion.div
            initial={{ opacity: 0, y: 50 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-6"
          >
            {/* Summary */}
            <div className="bg-white rounded-2xl shadow-lg p-8">
              <div className="flex items-center justify-between mb-6">
                <div>
                  <h3 className="text-2xl font-bold text-[#333333] mb-2">
                    Analysis Complete
                  </h3>
                  <p className="text-[#333333] opacity-80">
                    Document Type: {analysisResult.documentType}
                  </p>
                </div>
                <Button variant="accent" icon={Download} onClick={downloadReport}>
                  Download Report
                </Button>
              </div>

              {/* Rights Analysis */}
              <div className="space-y-4">
                <h4 className="text-xl font-semibold text-[#333333] mb-4">Your Rights Analysis:</h4>
                {analysisResult.rightsFound.map((right: any, index: number) => (
                  <div
                    key={index}
                    className={`p-4 rounded-xl border-l-4 ${
                      right.status === 'found' ? 'border-[#66BB6A] bg-green-50' :
                      right.status === 'missing' ? 'border-[#E53935] bg-red-50' :
                      'border-[#FFCA28] bg-yellow-50'
                    }`}
                  >
                    <div className="flex items-start gap-3">
                      {right.status === 'found' ? (
                        <CheckCircle className="h-6 w-6 text-[#66BB6A] mt-1" />
                      ) : (
                        <AlertCircle className="h-6 w-6 text-[#E53935] mt-1" />
                      )}
                      <div className="flex-1">
                        <h5 className="font-semibold text-[#333333] mb-1">{right.title}</h5>
                        <p className="text-[#333333] mb-2">
                          {language === 'en' ? right.description : right.urduDescription}
                        </p>
                        <span className={`inline-block px-3 py-1 rounded-full text-sm font-medium ${
                          right.status === 'found' ? 'bg-[#66BB6A] text-white' :
                          right.status === 'missing' ? 'bg-[#E53935] text-white' :
                          'bg-[#FFCA28] text-[#333333]'
                        }`}>
                          {right.status === 'found' ? 'Found' : 
                           right.status === 'missing' ? 'Missing' : 'Limited'}
                        </span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>

              {/* Recommendations */}
              <div className="mt-8 p-6 bg-[#FAFAFA] rounded-xl">
                <h4 className="text-xl font-semibold text-[#333333] mb-4">
                  {language === 'en' ? 'Recommendations:' : 'تجاویز:'}
                </h4>
                <ul className="space-y-2">
                  {analysisResult.recommendations.map((rec: string, index: number) => (
                    <li key={index} className="flex items-start gap-3">
                      <div className="w-2 h-2 bg-[#F06292] rounded-full mt-2"></div>
                      <span className="text-[#333333]">{rec}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Actions */}
              <div className="mt-8 flex flex-col sm:flex-row gap-4">
                <Button
                  variant="primary"
                  onClick={() => window.location.href = '/lawyers'}
                  className="flex-1"
                >
                  {language === 'en' ? 'Consult a Lawyer' : 'وکیل سے مشورہ کریں'}
                </Button>
                <Button
                  variant="secondary"
                  onClick={() => window.location.href = '/chat'}
                  className="flex-1"
                >
                  {language === 'en' ? 'Ask AI Questions' : 'اے آئی سے سوال پوچھیں'}
                </Button>
                <Button
                  variant="accent"
                  onClick={() => {
                    setUploadedFile(null);
                    setAnalysisResult(null);
                  }}
                  className="flex-1"
                >
                  {language === 'en' ? 'Scan Another' : 'دوسری اسکین کریں'}
                </Button>
              </div>
            </div>
          </motion.div>
        )}

        {/* Privacy Notice */}
        <div className="mt-8 p-6 bg-white rounded-xl border border-[#CE93D8]">
          <div className="flex items-start gap-3">
            <AlertCircle className="h-6 w-6 text-[#F06292] mt-1" />
            <div>
              <h4 className="font-semibold text-[#333333] mb-2">
                {language === 'en' ? 'Privacy & Security' : 'رازداری اور سیکیورٹی'}
              </h4>
              <p className="text-[#333333] text-sm leading-relaxed">
                {language === 'en' 
                  ? 'Your documents are analyzed securely and are not stored on our servers. All analysis is done locally and your privacy is protected.'
                  : 'آپ کی دستاویزات محفوظ طریقے سے تجزیہ کی جاتی ہیں اور ہمارے سرورز پر محفوظ نہیں کی جاتیں۔ تمام تجزیہ مقامی طور پر کیا جاتا ہے اور آپ کی رازداری محفوظ ہے۔'
                }
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Scan;